name: Juan Muscarsel
favicon: null
layout_spectrum: 0.19804720534011722
typography_spectrum: 0.8925852116663009
title: Graphic Designer
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.13529514870606363
  lightness: 0.3011550959199667
  saturation: 0.9052800741046667
  rhythmicContrast: 0.1454841704107821
purpose: []
